service: express-lontec-fun2

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:284507394080:table/LibraryTable

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/library/books
          method: GET
      - http:
          path: /api/library/books/{uid}
          method: GET
      - http:
          path: /api/library/books
          method: POST
      - http:
          path: /api/library/books/{uid}
          method: PUT
      - http:
          path: /api/library/books/{uid}
          method: DELETE
      - http:
          path: /api/post/article
          method: GET
      - http:
          path: /api/post/article
          method: POST

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LibraryTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true